global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3600s
  receiver: 'telegram'

receivers:
  - name: 'email'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'quocnvc@gmail.com'
        auth_password: "bixa gxjx udhx hfyb"
        from: 'quocnvc@gmail.com'
        to: 'cqvnno1@gmail.com'
        headers:
          subject: 'Prometheus Mail Alerts'
          
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7498607478:AAFub3sfjdw1rnj-Ni7IByYrV67EvYc-7zv'
        api_url: https://api.telegram.org
        chat_id: -4220896623
        message: '{{ template "telegram.yucca.message" . }}'

templates:
- '/templates/telegram.tmpl'